// Generated by CoffeeScript 1.6.1
(function() {
  var io;

  io = require('socket.io').listen(80);

  io.sockets.on('connection', function(socket) {
    return socket.on('message', function(data) {
      return socket.broadcast.emit('message', {
        message: data
      });
    });
  });

}).call(this);
